name: CI
on:
  push:
    branches: [master]
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ngcore
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - build: x86_64-linux
          os: ubuntu-latest
        - build: x86_64-macos
          os: macos-latest
        - build: x86_64-windows
          os: windows-latest
          target: x86_64-pc-windows-gnu
        - build: aarch64-linux
          os: ubuntu-latest
          target: aarch64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2

    - name: Analysis wasman
      run: go vet -v ./...

    - name: Test wasman
      run: go test -v ./...

    - name: Test wasman with race
      run: go test -race -v ./...
